# Generated by Django 5.1.4 on 2024-12-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0004_alter_buyer_name_alter_game_age_limited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
