# Generated by Django 5.1.4 on 2024-12-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0008_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='game',
            name='age_limited',
            field=models.BooleanField(default=False),
        ),
    ]
