# Generated by Django 5.1.4 on 2024-12-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0015_temporarybuyer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryBuyer',
        ),
    ]
