# Generated by Django 5.1.4 on 2024-12-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0017_alter_buyer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
