# Generated by Django 5.1.4 on 2024-12-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_rename_name_game_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='title',
            new_name='name',
        ),
    ]
