# Generated by Django 5.1.4 on 2024-12-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0006_alter_game_age_limited_alter_game_buyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='age_limited',
        ),
        migrations.RemoveField(
            model_name='game',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
