# Generated by Django 5.1.4 on 2024-12-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0007_news_remove_game_age_limited_remove_game_buyer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
