# Generated by Django 5.1.4 on 2024-12-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0009_alter_news_options_game_age_limited'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
